- README.md
#What
最終課題メルカリ制作のDB設計RADMEになります。
#Why
エンティティを可視化し、必要な設計図を構築することでプログラミングを効率化するためです。
> database_create

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/items/_buy.scss
- app/controllers/items_controller.rb
- app/views/items/_items-footer.html.haml
- app/views/items/_items-header.html.haml
- app/views/items/buy.html.haml
#WHAT
商品購入確認ページの実装
#WHY
アプリケーションの実装必須ページのため
> 購入確認ページ　実装

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/main_footer.scss
- app/views/items/_sell_btn.html.haml
- app/views/items/index.html.haml
- app/views/layouts/application.html.haml
- config/routes.rb
トップページを表示させるために、アクションの設定や部分テンプレートの設定を行った。
ビューを共有するために必要だから
> トップページを表示させるための設定

- app/assets/stylesheets/application.scss
トップページを表示させるために、application.scssに追記
ビューを共有するために必要だから
> application.scssの追記

- app/assets/stylesheets/application.scss
- app/views/items/_sell_btn.html.haml
- app/views/items/index.html.haml
Index.html.hamlの追加
トップページを表示させるため
> Index.html.hamlの追加

- app/assets/stylesheets/identification.scss
- app/views/users/_identification.html.haml
本人確認ページの作成
本人確認ページは情報を確認するために必要なため
_identification.html.hamlとidentification.scssを作成しました
> ユーザー本人確認ページの実装

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/items/_show.scss
- app/controllers/items_controller.rb
- app/views/items/show.html.haml
#WHAT
商品出品ページの実装
#WHY
アプリケーションの必須ページのため
> [WIP]商品詳細画面実装

- app/views/items/buy.html.haml
- app/views/items/new.html.haml
- app/views/items/show.html.haml
#WHAT
ビューの画像ファイルの参照先の修正
#WHY
エラーの解消のため
> 画像ファイル参照先修正

- Gemfile
- Gemfile.lock
- app/models/creditcard.rb
- db/migrate/20191225075628_create_creditcards.rb
- spec/factories/creditcards.rb
- spec/models/creditcard_spec.rb
#WHAT
payjpとcreditcardモデル、テーブルの作成
#WHY
ユーザー登録、商品購入機能実装で必要なため
> [WIP]payjpの導入

- app/models/creditcard.rb
- db/migrate/20191225075628_create_creditcards.rb
- db/schema.rb
#WHAT
クレジットのマイグレーション修正、アソシエーションの追加
#WHY
エラー解消のため
> [WIP]クレジットのDB修正

- app/assets/stylesheets/module/_adress.scss
- app/assets/stylesheets/module/_done.scss
- app/assets/stylesheets/module/_new_inform.scss
- app/assets/stylesheets/module/_pay.scss
- app/assets/stylesheets/module/_phone_number.scss
- app/assets/stylesheets/module/mypage.scss
- app/views/creditcards/_new_register_creditcard.html.haml
- app/views/users/index.html.haml
- app/views/users/update.html.haml
what
フロントの修正版
クレジットカードrender
why
修正が必要だったため。
> 修正版フロント・クレジットカードrender

- app/assets/javascripts/purchase.coffee
- app/assets/stylesheets/items/_show.scss
- app/assets/stylesheets/purchase.scss
- app/controllers/purchase_controller.rb
- app/helpers/purchase_helper.rb
- app/views/items/show.html.haml
- app/views/layouts/application.html.haml
- app/views/purchase/buy.html.haml
- config/routes.rb
- db/schema.rb
- spec/controllers/purchase_controller_spec.rb
- spec/helpers/purchase_helper_spec.rb
#WHAT
購入機能用のコントローラーの追加
ビューの修正
#WHY
購入きの実装の準備のため
> コントローラーまわり追加

- app/controllers/purchase_controller.rb
- app/models/creditcard.rb
- app/views/items/show.html.haml
#WHAT
クレジットのリダイレクト、バリデーションの設定
リンクパスのid修正
#WHY
アプリの機能向上のため
> リダイレクト、バリデーションの設定

- spec/controllers/creditcards_controller_spec.rb
- spec/factories/creditcards.rb
- spec/models/creditcard_spec.rb
#WHAT
クレジットカードモデル単体テスト
#WHY
仕様確認のため
> クレジットカードモデル単体テスト

- app/assets/javascripts/application.js
- app/assets/javascripts/comment.js
- app/assets/javascripts/purchase.coffee
- app/assets/stylesheets/comments.scss
- app/assets/stylesheets/items/_show.scss
- app/controllers/comments_controller.rb
- app/controllers/items_controller.rb
- app/helpers/comments_helper.rb
- app/models/comment.rb
- app/models/item.rb
- app/models/user.rb
- app/views/comments/create.json.jbuilder
- app/views/items/show.html.haml
- config/application.rb
- config/routes.rb
- db/migrate/20200108022002_create_comments.rb
- spec/controllers/comments_controller_spec.rb
- spec/factories/comments.rb
- spec/helpers/comments_helper_spec.rb
- spec/models/comment_spec.rb
#WHTA
コメント機能の実装
コメント非同期の実装
#WHY
機能拡張のため
> Add comments

- spec/factories/comments.rb
- spec/models/comment_spec.rb
#WHAT
コメントモデル単体テスト
#WHY
仕様確認のため
> コメントモデル単体テスト

- app/controllers/purchase_controller.rb
#WHAT
ログイン機能連携
購入完了画面へのリンク設定
#WHY
開発上必須のため
> ログイン機能連携、完了画面ルーティング

- app/assets/javascripts/comment.js
- app/controllers/comments_controller.rb
- app/views/items/show.html.haml
#WHAT
ログイン機能対応、ターボリンクス対応の追加
#WHY
必須機能のため
> ログイン機能連携、ターボリンクス対応

- app/views/items/show.html.haml
#WHAT
ブランドが空のときにエラーになるので、空のときはなしと表示するようにする
> ブランド欄が空の時の対応

- app/assets/stylesheets/application.scss
- app/views/common/_sub_header.html.haml
- config/routes.rb
マイページのヘッダーにもカテゴリィリストが表示されるように対応
必要な機能のため
> ヘッダーのリンク設定

- app/assets/stylesheets/application.scss
- app/controllers/comments_controller.rb
- app/controllers/purchase_controller.rb
#WHAT
仮置きのリダイレクトを正規のものへ変更
#WHY
設計通りのコードにするため
> [WIP]コントローラーリダイレクト変更

- app/models/address.rb
- app/models/phone_number.rb
- app/models/user.rb
- db/schema.rb
#WHAT
ユーザー登録の正規表現アップデート
#WHY
出来るだけ本物に近いものを作り上げるため
> [WIP]REGEX_UPDATE

- app/assets/javascripts/prefecture.js
都道府県JSパス修正
全ページがロードした後に発火してappendchild nullエラーがでる。
パスを指定して修正するため
> js_address_path_identified

- app/assets/javascripts/prefecture.js
- app/models/address.rb
> path_reconfiguration

- app/controllers/users/registrations_controller.rb
> binding_pry_delete

- app/controllers/items_controller.rb
- app/controllers/purchase_controller.rb
- app/views/items/show.html.haml
#WHAT
購入機能のガード節設定
#WHY
異常系動作対策のため
> 購入機能のガード節設定

- app/models/address.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.haml
> regex_select_box

- app/assets/stylesheets/application.scss
- app/views/items/show.html.haml
- config/routes.rb
#WHAT
ルートの追記
scss のレンダーの追記
#WHY
コンフリクト修正で消去したため、改めて記載
> [WIP]fix_admin

- app/views/items/show.html.haml
> 編集するボタンの追加

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.haml
- config/environments/production.rb
- db/schema.rb
#WHAT
Google Analytics
#WHY
analyze active users
> google_analytics

- app/views/layouts/application.html.haml
#WHAT
GOOGLE ANALYTICS、グーグル参照コード
> google_referenced_setting

- app/views/common/_side_bar.html.haml
- app/views/items/show.html.haml
#WHAT
サイドバーにクレジット編集画面へのリンク追加
商品詳細ページのボタン表示の条件分岐修正
#WHY
> リンク修正、条件分岐修正

- app/assets/stylesheets/admin/items_show.scss
- app/assets/stylesheets/admin/users_show.scss
- app/assets/stylesheets/creditcard/new.scss
- app/assets/stylesheets/items/_buy.scss
- app/assets/stylesheets/items/_new.scss
- app/assets/stylesheets/items/_show.scss
- app/assets/stylesheets/main_header.scss
- app/assets/stylesheets/module/_adress.scss
- app/assets/stylesheets/module/_done.scss
- app/assets/stylesheets/module/_new_inform.scss
- app/assets/stylesheets/module/_phone_number.scss
- app/assets/stylesheets/module/_signup_creditcard.scss
- app/assets/stylesheets/new_items.scss
- app/assets/stylesheets/user_profiles/index.scss
- app/controllers/items_controller.rb
- app/helpers/items_helper.rb
- app/models/category.rb
- app/views/admin/items_show.html.haml
- app/views/admin/trading_show.html.haml
- app/views/categories/_search_results.html.haml
- app/views/items/_search_result.html.haml
- app/views/items/_sell_btn.html.haml
- app/views/items/_sell_items_list.html.haml
- app/views/items/_sell_items_list_top.html.haml
- app/views/items/show.html.haml
売れた商品にsold表示を出す
ビューの微調整
売れた商品を判別できるようにするため
> Soldout表示などなど

- app/assets/stylesheets/show_transactions.scss
- app/views/users/purchase.html.haml
- app/views/users/purchased.html.haml
> 売り切れアイコン追加
